<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MUTHULAKSHMI" failures="1" tests="5" name="Test" time="0.063" errors="0" timestamp="2024-12-30T01:06:58 IST">
  <testcase classname="com.qa.pages.RetryRunTime" name="Test1" time="0.014">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.qa.pages.RetryRunTime" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.qa.pages.RetryRunTime" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.qa.pages.RetryRunTime" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.pages.RetryRunTime.Test1(RetryRunTime.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="com.qa.pages.RetryRunTime" name="Test2" time="0.001"/>
</testsuite> <!-- Test -->
